In [2]:
import numpy as np
import tensorflow as tf

In [3]:
xy = np.loadtxt('data/data-01-test-score.csv', 
                delimiter = ',', dtype = np.float32)


In [5]:
xy

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]], dtype=float32)

- slicing

In [6]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [9]:
# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [10]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 74125.87 
Prediction:
 [[ -97.97548 ]
 [-125.531204]
 [-119.63226 ]
 [-130.88408 ]
 [ -97.18083 ]
 [ -73.47737 ]
 [ -96.67687 ]
 [ -69.63009 ]
 [-119.849915]
 [-113.02292 ]
 [ -94.84981 ]
 [ -97.18333 ]
 [-123.12849 ]
 [-102.0348  ]
 [ -98.348526]
 [-127.23244 ]
 [ -98.867004]
 [-114.5927  ]
 [-116.0939  ]
 [-103.143364]
 [-114.271835]
 [-117.84732 ]
 [-108.121216]
 [ -97.642044]
 [-128.60025 ]]
10 Cost: 30.150969 
Prediction:
 [[156.18059]
 [179.97653]
 [181.37044]
 [196.93935]
 [135.82033]
 [ 98.32233]
 [148.71326]
 [112.29014]
 [165.68762]
 [151.47653]
 [141.57265]
 [135.9532 ]
 [187.84074]
 [156.46175]
 [148.17581]
 [182.791  ]
 [147.31758]
 [179.8966 ]
 [180.36392]
 [162.11345]
 [173.48906]
 [168.76605]
 [166.23067]
 [158.58871]
 [188.01357]]
20 Cost: 26.434639 
Prediction:
 [[157.91562]
 [182.0969 ]
 [183.44089]
 [199.20308]
 [137.43883]
 [ 99.53335]
 [150.41109]
 [113.55245]
 [167.68819]
 [153.35225]
 [143.20976]
 [137.58629]
 [189.97134]
 [158.22261]
 [149.88766]
 [184.

540 Cost: 18.98112 
Prediction:
 [[156.94865 ]
 [182.56517 ]
 [183.02853 ]
 [199.16325 ]
 [137.86342 ]
 [100.66806 ]
 [150.5321  ]
 [113.804855]
 [169.0039  ]
 [155.62112 ]
 [143.39214 ]
 [138.6424  ]
 [189.15547 ]
 [157.06927 ]
 [150.29803 ]
 [185.66231 ]
 [147.90553 ]
 [181.95749 ]
 [181.29439 ]
 [162.84154 ]
 [175.71239 ]
 [171.4958  ]
 [168.09009 ]
 [158.42752 ]
 [190.2383  ]]
550 Cost: 18.868675 
Prediction:
 [[156.9319  ]
 [182.573   ]
 [183.02126 ]
 [199.16228 ]
 [137.87059 ]
 [100.68734 ]
 [150.53386 ]
 [113.808815]
 [169.0262  ]
 [155.65965 ]
 [143.39502 ]
 [138.66026 ]
 [189.14134 ]
 [157.04947 ]
 [150.30476 ]
 [185.67427 ]
 [147.8869  ]
 [181.9575  ]
 [181.2755  ]
 [162.82286 ]
 [175.71599 ]
 [171.50813 ]
 [168.08919 ]
 [158.39507 ]
 [190.23874 ]]
560 Cost: 18.757202 
Prediction:
 [[156.91519]
 [182.58076]
 [183.014  ]
 [199.1613 ]
 [137.87772]
 [100.70655]
 [150.53561]
 [113.81277]
 [169.04839]
 [155.698  ]
 [143.3979 ]
 [138.67802]
 [189.12726]
 [157.02974]
 [150.31143]
 [

950 Cost: 15.094892 
Prediction:
 [[156.31697]
 [182.86101]
 [182.75499]
 [199.12599]
 [138.1361 ]
 [101.3943 ]
 [150.59554]
 [113.94842]
 [169.84344]
 [157.06905]
 [143.5001 ]
 [139.31429]
 [188.6249 ]
 [156.32677]
 [150.54819]
 [186.11333]
 [147.20944]
 [181.95374]
 [180.58464]
 [162.13951]
 [175.84558]
 [171.96004]
 [168.05339]
 [157.20804]
 [190.25671]]
960 Cost: 15.016546 
Prediction:
 [[156.3029 ]
 [182.86763]
 [182.74892]
 [199.12514]
 [138.14224]
 [101.41046]
 [150.59686]
 [113.95147]
 [169.86214]
 [157.10118]
 [143.50249]
 [139.32921]
 [188.61314]
 [156.31033]
 [150.55368]
 [186.12337]
 [147.1941 ]
 [181.95354]
 [180.5689 ]
 [162.12393]
 [175.84848]
 [171.97037]
 [168.0525 ]
 [157.18098]
 [190.25717]]
970 Cost: 14.938912 
Prediction:
 [[156.28891 ]
 [182.87422 ]
 [182.74287 ]
 [199.12428 ]
 [138.14835 ]
 [101.426544]
 [150.59819 ]
 [113.95449 ]
 [169.88074 ]
 [157.1332  ]
 [143.50485 ]
 [139.34407 ]
 [188.60144 ]
 [156.29399 ]
 [150.55914 ]
 [186.13335 ]
 [147.17883 ]
 [181.95

1410 Cost: 12.118579 
Prediction:
 [[155.72862]
 [183.13954]
 [182.50188]
 [199.08998]
 [138.39565]
 [102.0703 ]
 [150.6481 ]
 [114.0695 ]
 [170.62505]
 [158.41061]
 [143.59851]
 [139.93803]
 [188.13573]
 [155.64403]
 [150.77473]
 [186.53319]
 [146.57426]
 [181.93977]
 [179.92839]
 [161.48906]
 [175.96358]
 [172.39197]
 [168.01405]
 [156.07979]
 [190.278  ]]
1420 Cost: 12.066312 
Prediction:
 [[155.71707]
 [183.14503]
 [182.49695]
 [199.08926]
 [138.40082]
 [102.08356]
 [150.64906]
 [114.07173]
 [170.64038]
 [158.43687]
 [143.60042]
 [139.95026]
 [188.12617]
 [155.63074]
 [150.7791 ]
 [186.54143]
 [146.56195]
 [181.93939]
 [179.91557]
 [161.47633]
 [175.96584]
 [172.40044]
 [168.01323]
 [156.05772]
 [190.27846]]
1430 Cost: 12.014513 
Prediction:
 [[155.70557]
 [183.15053]
 [182.49203]
 [199.08855]
 [138.40596]
 [102.09677]
 [150.65002]
 [114.07395]
 [170.65567]
 [158.46301]
 [143.60233]
 [139.96243]
 [188.11668]
 [155.6175 ]
 [150.78345]
 [186.54964]
 [146.54968]
 [181.939  ]
 [179.902

1920 Cost: 9.961088 
Prediction:
 [[155.19818]
 [183.39389]
 [182.27553]
 [199.0561 ]
 [138.63568]
 [102.67926]
 [150.68845]
 [114.16496]
 [171.32927]
 [159.61249]
 [143.68488]
 [140.49817]
 [187.70013]
 [155.03809]
 [150.97198]
 [186.91144]
 [146.01585]
 [181.91588]
 [179.34198]
 [160.90634]
 [176.06339]
 [172.78087]
 [167.973  ]
 [155.07083]
 [190.30164]]
1930 Cost: 9.927694 
Prediction:
 [[155.1889 ]
 [183.39838]
 [182.27159]
 [199.05551]
 [138.63995]
 [102.68992]
 [150.68909]
 [114.1665 ]
 [171.34161]
 [159.63345]
 [143.68637]
 [140.50797]
 [187.69258]
 [155.02759]
 [150.97537]
 [186.91809]
 [146.00624]
 [181.91534]
 [179.33179]
 [160.89618]
 [176.0651 ]
 [172.78769]
 [167.97224]
 [155.05324]
 [190.30211]]
1940 Cost: 9.894599 
Prediction:
 [[155.17964 ]
 [183.40285 ]
 [182.26765 ]
 [199.0549  ]
 [138.6442  ]
 [102.70054 ]
 [150.68971 ]
 [114.168015]
 [171.3539  ]
 [159.65434 ]
 [143.68785 ]
 [140.51772 ]
 [187.68504 ]
 [155.0171  ]
 [150.97874 ]
 [186.92467 ]
 [145.99664 ]
 [181.91