***
**Python 머신러닝 완벽 가이드 Section 1-1.numpy** [Link](https://www.inflearn.com/course/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D-%EC%99%84%EB%B2%BD%EA%B0%80%EC%9D%B4%EB%93%9C#)
1. Numpy ndarray 개요
2. ndarray의 데이터 세트 선택 : indexing
3. ndarray 의 정렬 
4. ndarray 선형대수 연산

*2차원의 데이터라면 numpy 보단 pandas*


In [1]:
import numpy as np

# Numpy ndarray 개요

1. np.array() : ndarray 생성 
2. ndarray.shape : ndarray 의 형태(shape)와 차원
3. ndarray.dtype : ndarray 의 데이터 값 type 
4. ndarray.astype() : ndarray 데이터 타입 변환
5. ndarray 의 axis 축
6. ndarray 를 편리하게 생성하기 : arange, zeros, ones
7. ndarray.reshape() : ndarray의 shape를 변경하는 

- ndarray 생성 np.array()

In [2]:
list1 = [1, 2, 3]
print("list1:",list1)
print("list1 type:",type(list1))

array1 = np.array(list1)
print("array1:",array1)
print("array1 type:", type(array1))

list1: [1, 2, 3]
list1 type: <class 'list'>
array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>


- ndarray 의 형태(shape)와 차원

In [3]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)


array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [4]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(\
                    array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


- ndarray 의 데이터 값 type
    - 숫자, 문자열, boolean 모두 가능
    - ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능
    - ndarray.dtype 으로 확인 가능
    

In [5]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


- ndarray 데이터 타입 변환
    - astype()
    - **대용량 데이터 다룰 시, 메모리 절약을 위해 형변환 특히 고려해야 함!**
    - ndarray 는 모두 메모리에 올라가기 때문에, 메모리의 절약을 위해 주로 사용
    - 0, 1, 2 와 같이 크지 않은 범위의 숫자를 위해서 64bit float 보다는 8bit, 16bit 형으로 변환하는 것이 메모리 절약

In [6]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


- ndarray 의 axis
    - ndarray의 shape 는 행, 열, 높이 단위로 부여되는 것이 아니라 axis0(행), axis1(열), axis2와 같이 axis 단위로 부여됨

In [7]:
array2 = np.array([[1,2,3],
                  [2,3,4]])

print(array2.shape, "axis0 : ", array2.shape[0], "axis1 : ", array2.shape[1])
print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

(2, 3) axis0 :  2 axis1 :  3
15
[3 5 7]
[6 9]


- ndarray 를 편리하게 생성하기 : arange, zeros, ones
    - 특정 크기와 차원을 가진 ndarray 를 연속값이나 0 또는 1 로 초기화 생성해야 할 경우 arange(), zeros(), ones()로 손쉽게 생성 가능
    - arange 는 python의 range, Iterator 와 비슷한 기능을 함
    - **주로 테스트용으로 데이터를 만들거나, 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용됨**

In [8]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)


[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [9]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


- ndarray의 shape를 변경하는 reshape()
    - reshape 는 ndarray를 특정 차원 및 형태로 변환, 변환 형태를 함수 인자로 부여

In [10]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


- reshape()에 -1 인자값 부여시, 가변적인 ndarray 형태 반환
    - **reshape()에 -1 인자값을 부여하여 특정 차원으로 고정된 가변적인 ndarray형태 변환**
    - **reshape()는 (-1, 1), (-1,)와 같은 형태로 주로 사용됨.**
    - 1차원 ndarray를 2차원으로 또는 2차원 ndarray를 1차원으로 변환 시 사용. 

In [11]:
array1 = np.arange(10)
print(array1)

#컬럼 axis 크기는 5에 고정하고 로우 axis크기를 이에 맞춰 자동으로 변환. 즉 2x5 형태로 변환 
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)
print('array2:\n', array2)

#로우 axis 크기는 5로 고정하고 컬럼 axis크기는 이에 맞춰 자동으로 변환. 즉 5x2 형태로 변환 
array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)
print('array3:\n', array3)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape: (5, 2)
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
array1 = np.arange(5)

# 1차원 ndarray를 2차원으로 변환하되, 컬럼axis크기는 반드시 1이여야 함.
array2d_1 = array1.reshape(-1, 1)
print("array2d_1 shape:", array2d_1.shape)
print("array2d_1:\n", array2d_1)

# 2차원 ndarray를 1차원으로 변환
array1d = array2d_1.reshape(-1,)
print("array1d shape:", array1d.shape)
print("array1d:\n", array1d)

array2d_1 shape: (5, 1)
array2d_1:
 [[0]
 [1]
 [2]
 [3]
 [4]]
array1d shape: (5,)
array1d:
 [0 1 2 3 4]


In [13]:
# 반드시 -1 값은 1개의 인자만 입력해야 함. 
array1.reshape(-1, -1)

ValueError: can only specify one unknown dimension

# ndarray의 데이터 세트 선택하기 – 인덱싱(Indexing)

1. 특정 위치의 단일값 추출 
2. Slicing 
3. Fancy Indexing 
4. ⭐️Boolean Indexing 

- 특정 위치의 단일값 추출 
    - 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환됨

In [14]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)

# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))


array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [15]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])


맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [16]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)


array1: [9 2 3 4 5 6 7 8 0]


In [17]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


- Slicing 
    - 연속된 인덱스 상의 ndarray 추출

In [18]:
array1 = np.arange(start=1, stop=10)
print(array1)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [19]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [20]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


- Fancy Indexing
    - 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 ndarray 반환
    - 불연속적인 값도 찾을 수 있음

In [21]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,2], 0:2]
print('array2d[[0,2], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1], 2] =>  [3, 6]
array2d[[0,2], 0:2] =>  [[1, 2], [7, 8]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


- ⭐️Boolean Indexing 
    - 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True 에 해당하는 인덱스 위치에 있는 ndarray 반환
    - 조건 필터일 & 검색을 동시에 할 수 있기 때문에 매우 자주 사용!


In [22]:
array1d = np.arange(start=1, stop=10)
print(array1d)

[1 2 3 4 5 6 7 8 9]


In [23]:
print(array1d > 5)

var1 = array1d > 5
print("var1:",var1)
print(type(var1))


[False False False False False  True  True  True  True]
var1: [False False False False False  True  True  True  True]
<class 'numpy.ndarray'>


In [24]:
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
print(array1d)
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

[1 2 3 4 5 6 7 8 9]
array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [25]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [26]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


In [35]:
array1d = np.arange(start=1, stop=10)
target = []

for i in range(0, 9):
    if array1d[i] > 5:
        target.append(array1d[i])

array_selected = np.array(target)
print(array_selected)

## 훨씬 효율적인 boolearn filtering
print(array1)
print(array1d[array1 > 5])


[6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


# ndarray 의 정렬 - sort(), argsort()

1. np.sort(), ndarray.sort() : 기본적으로 오름차순으로 정렬
     - 내림차순으로 정렬하기 위해서는 [::-1] 적용
2. np.argsort()


- np.sort()
    - 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
- ndarray.sort()
    - 원 행렬 자체를 정렬한 형태로 변환, 반환값은 None

In [28]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)

# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [29]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [30]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


- np.argsort()
    - **원본행렬 정렬 시, 정렬된 행렬의 원래 인덱스를 필요로 할 때!**
    - 정렬된 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [31]:
org_array = np.array([ 3, 1, 9, 5]) 
print("origin", org_array, "sorted: ", np.sort(org_array))

sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

origin [3 1 9 5] sorted:  [1 3 5 9]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [32]:
org_array = np.array([ 3, 1, 9, 5]) 
print("sorted:", np.sort(org_array)[::-1])

sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)


sorted: [9 5 3 1]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


# 선형대수 연산 

1. np.dot(A, B) : 행렬 내적
2. np.transpose(A) : 전치 행렬


- 행렬내적

In [33]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


- 전치행렬
    - [0, 1]인덱스의 값 ==> [1, 0]인덱스로 이동

In [34]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
