***
**Python 머신러닝 완벽 가이드 Section 1-numpy** [Link](https://www.inflearn.com/course/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D-%EC%99%84%EB%B2%BD%EA%B0%80%EC%9D%B4%EB%93%9C#)
1. Numpy ndarray 개요
2. ndarray의 데이터 세트 선택 : indexing
3. ndarray 의 정렬 
4. ndarray 선형대수 연산


In [1]:
import numpy as np

# Numpy ndarray 개요

1. np.array() : ndarray 생성 
2. ndarray.shape : ndarray 의 형태(shape)와 차원
3. ndarray.dtype : ndarray 의 데이터 값 type 
4. ndarray.astype() : ndarray 데이터 타입 변환
5. ndarray 의 axis 축
6. ndarray 를 편리하게 생성하기 : arange, zeros, ones
7. ndarray.reshape() : ndarray의 shape를 변경하는 

- ndarray 생성 np.array()

In [3]:
list1 = [1, 2, 3]
print("list1:",list1)
print("list1 type:",type(list1))

array1 = np.array(list1)
print("array1:",array1)
print("array1 type:", type(array1))

list1: [1, 2, 3]
list1 type: <class 'list'>
array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>


- ndarray 의 형태(shape)와 차원

In [4]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)


array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [7]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(\
                    array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


- ndarray 의 데이터 값 type
    - 숫자, 문자열, boolean 모두 가능
    - ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능
    - ndarray.dtype 으로 확인 가능
    

In [8]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


- ndarray 데이터 타입 변환
    - astype()
    - **대용량 데이터 다룰 시, 메모리 절약을 위해 형변환 특히 고려해야 함!**
    - ndarray 는 모두 메모리에 올라가기 때문에, 메모리의 절약을 위해 주로 사용
    - 0, 1, 2 와 같이 크지 않은 범위의 숫자를 위해서 64bit float 보다는 8bit, 16bit 형으로 변환하는 것이 메모리 절약

In [9]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


- ndarray 의 axis
    - ndarray의 shape 는 행, 열, 높이 단위로 부여되는 것이 아니라 axis0(행), axis1(열), axis2와 같이 axis 단위로 부여됨

In [12]:
array2 = np.array([[1,2,3],
                  [2,3,4]])

print(array2.shape, "axis0 : ", array2.shape[0], "axis1 : ", array2.shape[1])
print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

(2, 3) axis0 :  2 axis1 :  3
15
[3 5 7]
[6 9]


- ndarray 를 편리하게 생성하기 : arange, zeros, ones
    - 특정 크기와 차원을 가진 ndarray 를 연속값이나 0 또는 1 로 초기화 생성해야 할 경우 arange(), zeros(), ones()로 손쉽게 생성 가능
    - arange 는 python의 range, Iterator 와 비슷한 기능을 함
    - **주로 테스트용으로 데이터를 만들거나, 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용됨**

In [13]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)


[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [14]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


- ndarray의 shape를 변경하는 reshape()
    - reshape 는 ndarray를 특정 차원 및 형태로 변환, 변환 형태를 함수 인자로 부여

In [15]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


- reshape()에 -1 인자값 부여시, 가변적인 ndarray 형태 반환
    - **reshape()에 -1 인자값을 부여하여 특정 차원으로 고정된 가변적인 ndarray형태 변환**
    - **reshape()는 (-1, 1), (-1,)와 같은 형태로 주로 사용됨.**
    - 1차원 ndarray를 2차원으로 또는 2차원 ndarray를 1차원으로 변환 시 사용. 

In [17]:
array1 = np.arange(10)
print(array1)

#컬럼 axis 크기는 5에 고정하고 로우 axis크기를 이에 맞춰 자동으로 변환. 즉 2x5 형태로 변환 
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)
print('array2:\n', array2)

#로우 axis 크기는 5로 고정하고 컬럼 axis크기는 이에 맞춰 자동으로 변환. 즉 5x2 형태로 변환 
array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)
print('array3:\n', array3)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape: (5, 2)
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [18]:
array1 = np.arange(5)

# 1차원 ndarray를 2차원으로 변환하되, 컬럼axis크기는 반드시 1이여야 함.
array2d_1 = array1.reshape(-1, 1)
print("array2d_1 shape:", array2d_1.shape)
print("array2d_1:\n", array2d_1)

# 2차원 ndarray를 1차원으로 변환
array1d = array2d_1.reshape(-1,)
print("array1d shape:", array1d.shape)
print("array1d:\n", array1d)

array2d_1 shape: (5, 1)
array2d_1:
 [[0]
 [1]
 [2]
 [3]
 [4]]
array1d shape: (5,)
array1d:
 [0 1 2 3 4]


In [19]:
# 반드시 -1 값은 1개의 인자만 입력해야 함. 
array1.reshape(-1, -1)

ValueError: can only specify one unknown dimension

# ndarray의 데이터 세트 선택하기 – 인덱싱(Indexing)
